# Generated by Django 4.1.6 on 2023-02-08 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('user_id', models.CharField(max_length=20)),
                ('post_id', models.CharField(max_length=20)),
                ('sub_id', models.CharField(max_length=20)),
                ('up_vote', models.IntegerField()),
                ('down_vote', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('followers', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('creator', models.CharField(max_length=20)),
                ('post_id', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('descript', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('sub_reddits', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('profile_pic', models.TextField()),
            ],
        ),
    ]
