# Generated by Django 4.1.6 on 2023-02-13 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_me', '0008_alter_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
